### ISSUE TITLE
auth.session() and auth.user() return null in SPA app when called right after createClient

### ISSUE THREAD

**Issue by gawlk** [supabase/supabase-js#130]
# Bug report

## Describe the bug

`database.auth.session()` and `database.auth.user()` are both `null` when called right after `const database = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)` in a SPA app.

Steps to reproduce the behavior, please provide code snippets or a repository:

Just try the code

## Expected behavior

I expect `database.auth.session()` and `database.auth.user()` to not return `null` if a user is connected. I need to check that in my router to change the route if needed, yet can't without doing some custom code because of the `null` issue. The storage being synchronous, the returns shouldn't be `null`.

## System information

- OS: Mac OS
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: latest
- Version of Node.js: latest

**Comment by kiwicopple** [comment]
Hey @gawlk - I believe you're running into this one: https://github.com/supabase/gotrue-js/issues/36

I'm working on it this week, just trying to figure out the best way to handle it for expo apps .

If you think it's unrelated feel free to re-open 👍

**Comment by jadedigital** [comment]
Are we sure this bug is fixed?
I'm having a similar issue with a vue/nuxt SPA app.

Whenever I call `auth.signIn` it refreshes my page, and any code after is ignored.
Also, the first time I call it, it does not log in the user, it just refreshes the page. The user session in localstorage is null. If I call it again, it finally does load the user session into localstorage. But again, any code after `auth.signin()` is ignored, so I can't check for user or errors when logging in. The only thing I can do is put a function in `mounted` to check if `const user = this.$supabase.auth.user()` exists, and then I can router.push to a welcome page.

**Comment by silasabbott** [comment]
I'm having this exact same issue trying to redirect to/away from my login page. @gawlk, what did you end up doing?
