### ISSUE TITLE
package.json has incorrect version

### ISSUE THREAD

**Issue by wiverson** [supabase/supabase-js#221]
# Bug report

## Describe the bug

The package.json file has the version listed as "1.0.0" even though the current version is 1.22.0.

This breaks various dependency management systems, including things like https://www.webjars.org/ 

## To Reproduce

View the versionn number in the package.json file.

## Expected behavior

package.json version should match the release version. Hopefully set by the CI release system.

Incorrect version is set for the supabase-js/package.json - but that package does rely on the version numbers for the sub-packages (e.g. "@supabase/gotrue-js": "^1.17.0", etc). Probably should adopt the same version number system as the other packages.

**Comment by kiwicopple** [comment]
@soedirgo do you know if this is doable with the actions/automation? It won't break Conventional Commits right?

**Comment by soedirgo** [comment]
Hey @wiverson, the version number in the repo here is just a placeholder, it gets replaced by the CI before deploying to npm (npm would complain otherwise). If you want to depend on the version in the package.json file, you should use the tarballs from npm instead (it looks like webjars provide that option, but I haven't used it).

**Comment by wiverson** [comment]
Got it working in WebJars, will confirm that it works in Maven.

https://search.maven.org/artifact/org.webjars.npm/supabase__supabase-js/1.21.0/jar

<dependency>
  <groupId>org.webjars.npm</groupId>
  <artifactId>supabase__supabase-js</artifactId>
  <version>1.21.0</version>
</dependency>
