### ISSUE TITLE
User gets deleted/returns undefined on page refresh

### ISSUE THREAD

**Issue by anoushk1234** [supabase/supabase-js#339]
# Bug report
User gets deleted on page refresh
## Describe the bug
When i first load the nextjs app the user loads properly but when i refresh it the user object is returned as undefined from the session.

## To Reproduce
```
useEffect(() => {
    setSession(supabase.auth.session() as any);
   console.log(session,"sesh");
    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session as any);
      console.log(session,"sesh in");
      setUser(session?.user != null ? session?.user : {});
      setUserID(
        session?.user != null ? session?.user?.user_metadata?.provider_id : ""
      );
      
    });
  }, []);
  ``` 
 I've used discord third party auth so youll have to use that, put this in your nextjs app and youll see that on first load the session is console logged but on second it gives undefined

## Expected behavior
Should load user from db on evry refresh not just first

## System information

- OS: [Windows]
- Browser (if applies) [firefox]
- Version of supabase-js: [^1.28.0]
- Version of Node.js: [14.17.1]

**Comment by dthyresson** [comment]
Hi @anoushk1234 and thanks for reporting.

Just to clarify, when you say "delete", the actual user record in `auth.users` table is not physically deleted, but rather the user is no longer available in the session?

Also, I assume this example code to reproduce, but could you explain a little bit about the intent here:

```js
useEffect(() => {
    setSession(supabase.auth.session() as any);
   console.log(session,"sesh");
    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session as any);
      console.log(session,"sesh in");
      setUser(session?.user != null ? session?.user : {});
      setUserID(
        session?.user != null ? session?.user?.user_metadata?.provider_id : ""
      );
      
    });
  }, []);
```

1. useEffect -> on page load...
2. set the session to the current session (?)
3. which the triggers the auth state change - but, no not the first load because the event isn't registered to be listened to
4. so now reload and  ..
5.  set the session to the current session
6. which now triggers the supabase.auth.onAuthStateChange
7. and you set the session to the changed session?
8. and then set the current user on the session to that session's user?

Is this example code or is this code trying to do something specific -- like always refresh the session on page load and that is failing?

Just trying to understand the context a little more before I try to reproduce.

Thanks!

**Comment by dthyresson** [comment]
Also, the `setSession()` is meant to take the refresh token:

https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueClient.ts#L358

Maybe because what is being passed isn't being checked as a string or a valid refresh token, this fails here:

https://github.com/supabase/gotrue-js/blob/d7b334a4283027c65814aa81715ffead262f0bfa/src/GoTrueClient.ts#L366

```ts
  async setSession(
    refresh_token: string
  ): Promise<{ session: Session | null; error: ApiError | null }> {
    try {
      if (!refresh_token) {
        throw new Error('No current session.')
      }
      const { data, error } = await this.api.refreshAccessToken(refresh_token)
      if (error) {
        return { session: null, error: error }
      }
```

And thus the session is null and thus use is null, but the error is swallowed because the code in the use effect didn't handle the error returned?

If so, then it does seem that either the GoTrue client or server should perhaps better check for a valid looking refresh token?

**Comment by anoushk1234** [comment]
Hey @dthyresson this code is to load the current user object from the session, I actually have my own users table but I also need to load the logged in User to get the discord data like username,uid,avatar etc

I first used ```supabase.auth.user()``` in the useffect so the first time it loads the users is stored but it wasnt happening async since the useffect was running before the user was being stored in the cookie so first time it wud not load user and on refresh it wud load the user so then i tried ```supabase.auth.onAuthStateChange((_event, session)``` after going thru the docs which half solved my problem as on first load it wud work but after reloading it wud give user as undefined

The main objective here is to just get the logged in user object and make that persist on every load until the user chooses to sign out, hope that answers your question

**Comment by TJ-Projects3** [comment]
@anoushk1234 Hey, hope your doing good. How'd you end up fixing this issue? I'm having a similar issue where I refresh on my user information page and then all the data disappears and I cant perform any database (Supabase) or Supabase auth functions (GET, DELETE, etc.) I'm left with an infinite loading screen on that page, I think this might be a policy or session issue but how did you solve it?
