### ISSUE TITLE
Signups not allowed for otp - Phone provider

### ISSUE THREAD

**Issue by kresogalic8** [supabase/supabase-js#724]
Hey, I have a problem with a phone provider, I am using twillio as a phone provider and i do not want to create a user on `signInWithOtp`, and every time I trigger this method i got the same error.

This is the code I am running, phone is coming from the params of the method:

```
const { data, error } = await supabase.auth.signInWithOtp({
    phone,
    options: {
      shouldCreateUser: false,
    },
  });
```

Do i need to enable signups for otp?

I am using supabase **"@supabase/supabase-js": "^2.10.0"**

**Comment by ZHRhodes** [comment]
What's the error?

**Comment by kresogalic8** [comment]
Signups not allowed for otp

**Comment by monicakh** [comment]
This is actually intended behaviour. Since you've set shouldCreateUser to false, if the user doesn't exist yet and you're trying to call signInWithOtp, signInWithOtp will not create the user for you.

This means that the user will need to signup first and verify their phone number before calling signInWithOtp.

**Comment by akuul** [comment]
Isn't this a bit confusing if you take in consideration the `Passwordless email logins` HOW-TOS ?

It clearly states: `Improve the user experience by not requiring users to create and remember a password`, but if I still have to go through a normal password sign-up first, then what's the point ? 

https://supabase.com/docs/guides/auth/auth-email-passwordless?queryGroups=language&language=js

**Comment by biscarrosse** [comment]
as @akuul said, plus then your register email template is used and not magic link template

**Comment by Yanniswein** [comment]
Have you found a solution or a workaround for that? I'm surprised about this behavior too. Thx

**Comment by gsarpy** [comment]
> Have you found a solution or a workaround for that? I'm surprised about this behavior too. Thx

Maybe I am misunderstanding the problem here but what is the confusion? By including 

```
options: {
    shouldCreateUser: false, <--- this
},
```

you're explicitly telling Supabase auth to **_not_** create the user if they don't already exist. Meaning, they will need to already have an account to use OTP logins. By default, Supabase _will_ create the user via OTP logins but if you include that optional false param it will disable the default behavior forcing a different flow for signups e.g. a website email/password sign up flow. 

So, just don't include `shouldCreateUser: false,` and OTP should log the user in or automatically fall back to creating them if they don't already exist. Hope that answers your question.

**Comment by NalinKamboj** [comment]
I am facing the same issue as well. The difference is that I explicitly want "shouldCreateUser" to be false. I have manually created a user using the SQL editor in my users table already. When I try to signInWithOtp, I am getting the same error even though I am using the same phone number. 

`const { error } = await supabase.auth.signInWithOtp({
    phone,
    options: {
      shouldCreateUser: false, // 🔒 critical
      channel: "sms", // default, explicit is clearer
    },
  });`

**Comment by TheKnight-Dev** [comment]
I face the same issue, but with emails, as I would not like for the user to be created before he verifies his email with the OTP... This is why i need `shouldCreateUser: false`.

Because this is my case, i want the email to be verified before my sign up page, where there you enter the OTP(Verification Token in my case) sent to the email....

Any workarounds yet?

**Comment by jchauncey** [comment]
Ok here is how you get this to work -

```
    const { data, error } = await supabase.auth.signInWithOtp({
      email: email,
      options: {
        shouldCreateUser: true,
      },
    });
```

So this will send a confirmation email and also create the user. In your confirmation email template use the `{{ .Token }}` variable which will send the OTP token. You can use that to verify the user without needing them to create a password.

**Comment by Earnstein** [comment]
> Ok here is how you get this to work -
> 
> ```
>     const { data, error } = await supabase.auth.signInWithOtp({
>       email: email,
>       options: {
>         shouldCreateUser: true,
>       },
>     });
> ```
> 
> So this will send a confirmation email and also create the user. In your confirmation email template use the `{{ .Token }}` variable which will send the OTP token. You can use that to verify the user without needing them to create a password.

This works but "shouldCreateUser: false" sounds more like "Hey i won't create this user until they actually click the link and verify themselves".


This is what i thought it does, the team should consider changing the flag to "disable otp" or something else cause that is confusing.

**Comment by Abhijit-Jha** [comment]
Whats the fix? I am also facing the same issue 
```
const { error: otpError } = await supabase.auth.signInWithOtp({
        email : email,
        options: {
          shouldCreateUser: false // Explicitly prevent user creation
        }
      });
```

**Comment by chainmywallet** [comment]
I'm facing the same issue, it should work refering to these docs: https://supabase.com/docs/guides/auth/auth-email-passwordless

**Comment by mandarini** [comment]
Does this issue persist? If yes, can you please provide a simple reproduction repository? This will help me verify that the behavior is broken, and I will reopen and prioritize this issue! Thank you everyone for your patience and contribution! @chainmywallet @Abhijit-Jha
