### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by Hexagon** [supabase/supabase-js#739]
# Chore

## Describe the chore

- Publish on deno.land/x
- Docs on how to install on Deno

## Additional context

It would be nice with "official support" for Deno!

**Comment by 5hee75** [comment]
@Isaiah-Hamilton

Maybe this should be opened as a separate issue, but I am encountering an error when using the `@supabase/auth-helpers-shared` package from `esm.sh`, but the issue comes from that packages own type imports from the `@supabase/supabase-js` package.

```
Error: Module not found "https://esm.sh/v113/@supabase/supabase-js@2.12.1/dist/module/lib/types/dist/module/index.d.ts".
```

I can import the supabase-js package directly using that URL up to the version number, and using the auth helper package is working great locally, but this error is thrown when trying to bundle and deploy my function.  Is it possible the package is somehow incomplete in `esm.sh` (specifically the type declarations)?

Auth Helper Package - `https://esm.sh/@supabase/auth-helpers-shared@0.3.0`

**Comment by Isaiah-Hamilton** [comment]
@5hee75 can you open a separate issue.

**Comment by 5hee75** [comment]
@Isaiah-Hamilton 

https://github.com/supabase/supabase-js/issues/744

**Comment by Hexagon** [comment]
@Isaiah-Hamilton Why not? If you make a couple of small adjustments to the codebase this library would work in Deno (and Node, and Bun) ootb, without using esm.sh. Would be great imho!

**Comment by 5hee75** [comment]
@Hexagon what are some of those adjustments that need to be made to make it work?  Might be worth putting a PR together, if it's not too crazy.

**Comment by Hexagon** [comment]
Havn't looked at the codebase, but I'dlay it out like: make a fork, try to include it locally with deno, and adjust til it works :) Either run Deno agains the actual source (if possible), or make an esm build of it.

**Comment by Hexagon** [comment]
Resolved by supabase-js being available on jsr
