### ISSUE TITLE
Add transactions for read and write operations on one or more documents

### ISSUE THREAD

**Issue by CodeByCorey** [supabase/supabase-js#87]
# Feature request

Add transactions for read and write operations on one or more documents.

## Is your feature request related to a problem? Please describe.

If I make multiple requests to modify a row, it could lead to an improper update.

Example

First Request: 
1. fetch a row,
2. increment the value
3. update row

Second request:
1. fetches row before step 3 runs on first request
2. first request step 3 runs
2. Increments value on stale row
4. Update row with incremented value on stale data

## Describe the solution you'd like

Firebase offers [transactions](https://firebase.google.com/docs/firestore/manage-data/transactions)
> In the case of a concurrent edit, Cloud Firestore runs the entire transaction again. For example, if a transaction reads documents and another client modifies any of those documents, Cloud Firestore retries the transaction. This feature ensures that the transaction runs on up-to-date and consistent data.

## Describe alternatives you've considered

Instead of incrementing a value, just inserting a new row into a different table and using total row count.
This solves my issue but increases storage size. 

Transactions would still be a great improvement for other use cases.

**Comment by kiwicopple** [comment]
Hey @CodeByCorey, this would be done as a Stored Procedure, which you can then call using `rpc()`: https://supabase.io/docs/client/rpc

Postgres introduced transations into stored procedures in PG11, an Supabase is running on PG12. Here is an example of a stored procedure with a commit/rollback: https://www.postgresql.org/docs/current/plpgsql-transactions.html

Does that help?

**Comment by steve-chavez** [comment]
@CodeByCorey Also note that you can already rollback by raising an error on regular postgres functions:

```sql
CREATE OR REPLACE FUNCTION just_fail() RETURNS json AS $$
BEGIN
  -- do some logic here
 -- RETURN
  -- in case of an error, fail:
  RAISE EXCEPTION 'I refuse!'
    USING DETAIL = 'Pretty simple',
          HINT = 'There is nothing you can do.';
 -- the above will cause a rollback
END 
$$ LANGUAGE plpgsql;

-- the above message will show on the error attribute when calling the function through supabase-js
const { data, error } = await supabase.rpc('just_fail')
console.log(error);
{
  "message":"I refuse!",
  "details":"Pretty simple",
  "hint":"There is nothing you can do.",
  "code":"P0001"
}
```

**Comment by kiwicopple** [comment]
closing this for now Corey - but feel free to reopen if you have any questions

**Comment by tawjaw** [comment]
@steve-chavez can we change owner to authenticated on functions similar to views?
To apply RLS

`ALTER FUNCTION just_fail OWNER TO authenticated;`

**Comment by tawjaw** [comment]
I should have read the [docs](https://postgrest.org/en/v7.0.0/schema_structure.html#functions) before asking


If I understood correctly, first I have to revoke execute to all the functions from PUBLIC

`ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC; `

And then I can grant access on specific functions to authenticated users

`GRANT EXECUTE ON FUNCTION  just_fail TO authenticated; `


However it doesn't say anything specific about row-level-security like it explains in Views 

What happens if I select from a table with RLS inside the function?

**Comment by steve-chavez** [comment]
@tawjaw Functions work normally for RLS - the calling role privileges will be applied by default(SECURITY INVOKER). So no need for a previous `ALTER OWNER` there.

It's possible to get a similar behavior to ALTER OWNER on VIEWs with `SECURITY DEFINER`.

Check this for more details: https://postgrest.org/en/v7.0.0/schema_structure.html#security-definer

**Comment by tawjaw** [comment]
Thank you @steve-chavez 
Sorry I've been asking a lot.. before I started using supabase I didn't know RLS existed. the concept is still new to me.

**Comment by steve-chavez** [comment]
@tawjaw No problem! I do realize the privileges around VIEWs and FUNCTIONs are a bit confusing at first. Feel free to ping me anytime you have questions :-]

**Comment by tawjaw** [comment]
Thanks @steve-chavez 
I appreciate it.

I'm starting a test supabase project and just going to play with views and functions from the client side to understand it fully

**Comment by churichard** [comment]
I think this should be reopened. There are use cases where a rpc would not be able to work, whereas a transaction (similar to what Firebase has) would. Mainly, this is because you can have arbitrary logic or call libraries inside a Firebase transaction (which I think a rpc does not support).

For example, you might imagine a scenario where Record A is stored in the database and is also locally cached on a device for offline editing. You don't necessarily want to replace the record in the database with the locally cached record, because the record could have been updated from other devices. Instead, you might want to implement some complex business logic to merge the database record together with the locally cached record. You could do this inside a transaction in application logic, but not in a rpc implemented on the database.

Specifically, I'd be looking for the following two properties:
- Roll back all of the database operations if any of them fail or if an error occurs within the transaction
- Ensure that Record A in the database is not changed during the transaction (so we are always operating on the most up-to-date record)

Let me know if what I described above actually would be possible somehow currently, either with a rpc or through some other mechanism. Otherwise, having a transaction similar to what Firebase has seems like the ideal solution to me.

**Comment by steve-chavez** [comment]
> you might want to implement some complex business logic to merge the database record together with the locally cached record. You could do this inside a transaction in application logic, but not in a rpc implemented on the database.

Hmm.. Couldn't you send the local record as an argument of the rpc?  That way you could do the merge inside the SQL function.

**Comment by churichard** [comment]
In my case, the records are JSON objects and I want to use a JS library to do the merge.

For my specific use case (not particularly relevant but in case you're curious), this is the library I'd like to use: https://github.com/yjs/yjs. You can imagine it as accepting two JSON objects (the "master" copy from the database and the locally updated copy) and returning a JSON object with the changes merged together (even if the locally updated copy was updated on an outdated JSON object). I think it's a little hard to do this kind of merge in a SQL function, even if I wasn't using a library and wanted to write some logic myself.

**Comment by kiwicopple** [comment]
> accepting two JSON objects (the "master" object from the database and the locally updated object) and returning a JSON object with the changes merged together with no conflicts

I think this is getting more into the "offline support" or "conflict resolution" territory. As you point out, CRDTs could solve this (and we are even chatting to the Yjs maintainer about this), but note that it would need to be for a single database field rather than an entire row (although Automerge looks like they are [working on](https://github.com/automerge/automerge#table) something here too). CRDTs are specific data types (text, counters, etc), whereas Postgres supports everything from numerics to Geometry - we'd need a conflict resolution strategy for every data type, or just blindly go with a "last write wins" strategy (and we would need transaction timestamps).

@churichard - can you please provide some code (which you are using for your Firebase), and perhaps we can see if the same can be done using a `jsonb` column?

**Comment by churichard** [comment]
>  As you point out, CRDTs could solve this (and we are even chatting to the Yjs maintainer about this)

It would be wonderful if there was first party support for offline support / conflict resolution! It would definitely solve the use case I mentioned earlier.

If we generalize a bit more, though, I feel like it might still be useful to have a transaction such that you're doing SELECTs, performing arbitrary transforms on the data, and then doing UPDATEs with the transformed data, while guaranteeing that the SELECTed data has not changed in the meantime (basically the field or row is locked).

I think you can probably imagine a scenario where this might be useful, but if you want a concrete example, here's one from the project I'm working on where I:
1. Get a field from a record (`content` is a `jsonb` field): https://github.com/churichard/notabase/blob/06926ce4561ef2862075f8b496eacf9e649c46c9/editor/useBacklinks.ts#L119-L123
2. Perform some operations on it (using a JS library): https://github.com/churichard/notabase/blob/06926ce4561ef2862075f8b496eacf9e649c46c9/editor/useBacklinks.ts#L129-L139
3. Update the field: https://github.com/churichard/notabase/blob/06926ce4561ef2862075f8b496eacf9e649c46c9/editor/useBacklinks.ts#L152-L155

The main thing in this use case is making sure that the record's fields do not change while we're doing the operations. This sounds like a case where a transaction would be useful, but let me know if there is a better or alternative way of doing this.

> but note that it would need to be for a single database field rather than an entire row 

Yeah, my use case about merging two JSON objects is just for single database field on a row (apologies if that was unclear).

> @churichard - can you please provide some code (which you are using for your Firebase), and perhaps we can see if the same can be done using a `jsonb` column?

I'm not using Firebase for my current project so I don't have any specific code to share. I only draw the parallel to Firebase transactions since I've worked with them in previous projects and know that it would be possible with the way that they work.

**Comment by gitbugr** [comment]
https://www.postgresql.org/docs/9.1/sql-begin.html

postgres has transactions outside of procedures, however it would require a way to keep a single user's connection open from what I understand. Not sure how well that would work with supabase.

it'd be super nice/useful if we could have a `begin` `commit` `rollback` methods accessible from the library.

**Comment by miketromba** [comment]
I'm unable to comment on the implementation feasibility of this on Postgres, but I find that Firebase's batching API is a super elegant and dev-friendly way of handling batches / transactions / atomic operations. An API like this would be amazing. Having to learn and use RPCs for atomic / batched write operations is annoying.

Firebase docs on transactions / batched writes: https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes

```js
// Example of firebase batching API from their docs:
import { writeBatch, doc } from "firebase/firestore"; 

// Get a new write batch
const batch = writeBatch(db);

// Set the value of 'NYC'
const nycRef = doc(db, "cities", "NYC");
batch.set(nycRef, {name: "New York City"});

// Update the population of 'SF'
const sfRef = doc(db, "cities", "SF");
batch.update(sfRef, {"population": 1000000});

// Delete the city 'LA'
const laRef = doc(db, "cities", "LA");
batch.delete(laRef);

// Commit the batch
await batch.commit();
```
